"""Availability response schemas. Slots are generated by the backend."""

from datetime import date, datetime

from pydantic import BaseModel, ConfigDict


class SlotPublic(BaseModel):
    model_config = ConfigDict(ser_json_timespec="seconds")

    start_datetime: datetime
    end_datetime: datetime


class AvailabilityResponse(BaseModel):
    doctor_id: int
    date: date
    slot_duration_minutes: int
    is_active: bool
    slots: list[SlotPublic]
